spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clinic_db}
    username: ${DB_USERNAME:clinic}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
  h2:
    console:
      enabled: false
